import type { CSSProperties } from 'react';

// Близко к стилям amoCRM: PT Sans, серые рамки, синие акценты.
export const s = {
  root: { fontFamily: '"PT Sans", Arial, sans-serif', fontSize: 14, color: '#313942', lineHeight: 1.4 },
  block: { padding: '12px 0', borderBottom: '1px solid #e8eaeb' },
  label: { color: '#92989b', fontSize: 12, marginBottom: 4 },
  row: { display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' },
  col: { display: 'flex', flexDirection: 'column', gap: 6 },
  badgeOk: { display: 'inline-block', padding: '2px 8px', borderRadius: 3, background: '#e5f6e0', color: '#2c7a18' },
  badgeBad: { display: 'inline-block', padding: '2px 8px', borderRadius: 3, background: '#fde8e8', color: '#b02a2a' },
  badgeWarn: { display: 'inline-block', padding: '2px 8px', borderRadius: 3, background: '#fff4d6', color: '#8a5a00' },
  muted: { color: '#92989b' },
  small: { fontSize: 12 },
  error: { color: '#b02a2a' },
  button: {
    height: 36,
    padding: '0 16px',
    border: '1px solid #4c8bf7',
    borderRadius: 3,
    background: '#4c8bf7',
    color: '#fff',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  buttonGhost: {
    height: 32,
    padding: '0 12px',
    border: '1px solid #d4d5d8',
    borderRadius: 3,
    background: '#fff',
    color: '#313942',
    cursor: 'pointer',
    fontFamily: 'inherit',
  },
  input: { height: 36, padding: '0 8px', border: '1px solid #d4d5d8', borderRadius: 3, fontFamily: 'inherit', boxSizing: 'border-box', width: '100%' },
  textarea: { padding: 8, border: '1px solid #d4d5d8', borderRadius: 3, fontFamily: 'inherit', boxSizing: 'border-box', width: '100%', minHeight: 90, resize: 'vertical' },
  select: { height: 36, padding: '0 8px', border: '1px solid #d4d5d8', borderRadius: 3, fontFamily: 'inherit' },
  tabs: { display: 'flex', flexWrap: 'wrap', gap: 4, borderBottom: '1px solid #e8eaeb', marginBottom: 16 },
  tab: { padding: '8px 12px', border: 'none', background: 'none', cursor: 'pointer', fontFamily: 'inherit', fontSize: 14, color: '#313942', borderBottom: '2px solid transparent' },
  tabActive: { borderBottom: '2px solid #4c8bf7', color: '#4c8bf7' },
  card: { border: '1px solid #e8eaeb', borderRadius: 4, padding: 10, background: '#fff' },
} satisfies Record<string, CSSProperties>;
